/**
 * Output exporters: DOCX, PDF, plain TXT, and LMS-ready blocks.
 * All run client-side so the package can be downloaded directly.
 */

import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  PageOrientation,
  ShadingType,
} from "docx";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";

export type DesignPayload = {
  context: any;
  lens: string;
  outcomes: any[];
  brief: any;
  integrity: any;
  rubric: any;
  alignmentReport?: any;
  patoisMode?: boolean;
};

const ATTRIBUTION =
  "Frameworks © Dr. Rohan Jowallah, Ed.D. — CARE · CRAFT · ACRE · Sovereign AI. Generated by the Sovereign AI Learning Designer.";

const safeFilename = (s: string | undefined, fallback = "assignment") =>
  (s || fallback).replace(/[^a-z0-9]+/gi, "-").toLowerCase().replace(/^-+|-+$/g, "");

/* ---------------- Plain text ---------------- */

export function buildPlainText(p: DesignPayload): string {
  const lines: string[] = [];
  const push = (s = "") => lines.push(s);
  const rule = "─".repeat(60);

  push(p.brief?.title || "Assignment");
  push(rule);
  push(`Course: ${p.context.courseTitle}`);
  push(`Discipline: ${p.context.discipline}`);
  push(`Level: ${p.context.level}`);
  push(`Region: ${p.context.region}`);
  push(`Modality: ${p.context.modality}`);
  push(`Time on task: ${p.context.timeOnTask}`);
  push(`AI stance: ${p.context.aiAccess}`);
  push(`Reflection lens: ${p.lens}`);
  if (p.patoisMode) push(`Register: Patois-aware mode enabled`);
  push("");

  if (p.brief) {
    push("SUMMARY");
    push(p.brief.summary);
    push("");
    push("SCENARIO");
    push(p.brief.scenario);
    push("");
    push("TASKS");
    p.brief.tasks.forEach((t: string, i: number) => push(`${i + 1}. ${t}`));
    push("");
    push("DELIVERABLES");
    p.brief.deliverables.forEach((d: string) => push(`• ${d}`));
    push("");
  }

  if (p.outcomes.length) {
    push("LEARNING OUTCOMES");
    p.outcomes.forEach((o: any, i: number) => push(`${i + 1}. ${o.statement}  [${o.bloomLevel}]`));
    push("");
  }

  if (p.brief?.criticalReflectionPrompts) {
    push("CARE REFLECTION PROMPTS");
    p.brief.criticalReflectionPrompts.forEach((q: any) => push(`${q.stage}: ${q.prompt}`));
    push("");
  }

  if (p.integrity) {
    push("AI INTEGRITY & SOVEREIGNTY STATEMENT");
    push("Permitted uses:");
    p.integrity.permittedUses.forEach((u: string) => push(`  • ${u}`));
    push("Restricted uses:");
    p.integrity.restrictedUses.forEach((u: any) => push(`  • ${u.item} — ${u.reason}`));
    push("Disclosure: " + p.integrity.disclosureRequirement);
    if (p.patoisMode && p.integrity.studentFacingPatois) {
      push("Disclosure (Patois): " + p.integrity.studentFacingPatois);
    }
    push("CARE reflection: " + p.integrity.careReflection);
    push("ACRE evaluation: " + p.integrity.acreEvaluation);
    push("Sovereignty: " + p.integrity.sovereigntyNote);
    push("");
  }

  if (p.rubric) {
    push("RUBRIC");
    p.rubric.criteria.forEach((c: any) => {
      push(`${c.name}  (${c.weight}%)  outcomes: ${(c.outcomesAddressed || []).join(", ")}`);
      ["Distinguished", "Proficient", "Developing", "Emerging"].forEach((lvl) =>
        push(`  ${lvl}: ${c.levels[lvl]}`)
      );
      push("");
    });
  }

  if (p.alignmentReport) {
    push("ALIGNMENT AUDIT");
    push(`Overall: ${p.alignmentReport.overallScore}`);
    push(p.alignmentReport.summary);
    push("");
  }

  push(rule);
  push(ATTRIBUTION);
  return lines.join("\n");
}

export function downloadTxt(p: DesignPayload) {
  const text = buildPlainText(p);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  saveAs(blob, `${safeFilename(p.brief?.title)}-sovereign-package.txt`);
}

/* ---------------- LMS-ready Markdown ---------------- */

export function buildLmsBlock(p: DesignPayload): string {
  const lines: string[] = [];
  const push = (s = "") => lines.push(s);

  push(`# ${p.brief?.title || "Assignment"}`);
  push("");
  if (p.brief?.summary) {
    push(`> ${p.brief.summary}`);
    push("");
  }

  push(`**Course:** ${p.context.courseTitle}  `);
  push(`**Level:** ${p.context.level}  `);
  push(`**Region:** ${p.context.region}  `);
  push(`**Modality:** ${p.context.modality}  `);
  push(`**Time on task:** ${p.context.timeOnTask}  `);
  push("");

  if (p.outcomes.length) {
    push(`## Learning outcomes`);
    p.outcomes.forEach((o: any, i: number) => push(`${i + 1}. ${o.statement} _(${o.bloomLevel})_`));
    push("");
  }

  if (p.brief) {
    push(`## Scenario`);
    push(p.brief.scenario);
    push("");
    push(`## Tasks`);
    p.brief.tasks.forEach((t: string, i: number) => push(`${i + 1}. ${t}`));
    push("");
    push(`## Deliverables`);
    p.brief.deliverables.forEach((d: string) => push(`- ${d}`));
    push("");
    if (p.brief.criticalReflectionPrompts?.length) {
      push(`## Reflection prompts (CARE)`);
      p.brief.criticalReflectionPrompts.forEach((q: any) =>
        push(`- **${q.stage}** — ${q.prompt}`)
      );
      push("");
    }
  }

  if (p.integrity) {
    push(`## AI integrity statement`);
    push(`### Permitted uses`);
    p.integrity.permittedUses.forEach((u: string) => push(`- ${u}`));
    push(``);
    push(`### Restricted uses`);
    p.integrity.restrictedUses.forEach((u: any) => push(`- **${u.item}** — ${u.reason}`));
    push(``);
    push(`### Disclosure`);
    push(`> ${p.integrity.disclosureRequirement}`);
    if (p.patoisMode && p.integrity.studentFacingPatois) {
      push(``);
      push(`> _Patois version:_ ${p.integrity.studentFacingPatois}`);
    }
    push(``);
  }

  if (p.rubric) {
    push(`## Rubric`);
    push(``);
    const headers = ["Criterion", "Weight", "Distinguished", "Proficient", "Developing", "Emerging"];
    push(`| ${headers.join(" | ")} |`);
    push(`| ${headers.map(() => "---").join(" | ")} |`);
    p.rubric.criteria.forEach((c: any) => {
      const row = [
        c.name,
        `${c.weight}%`,
        c.levels.Distinguished,
        c.levels.Proficient,
        c.levels.Developing,
        c.levels.Emerging,
      ].map((s: string) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " "));
      push(`| ${row.join(" | ")} |`);
    });
    push(``);
  }

  push(`---`);
  push(`_${ATTRIBUTION}_`);
  return lines.join("\n");
}

/* ---------------- DOCX ---------------- */

const JAM_GREEN = "006B3C";
const JAM_GOLD = "C99A00";
const CREAM = "FFFBEF";

function h1(text: string) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, color: JAM_GREEN, bold: true, size: 36 })],
  });
}
function h2(text: string) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 200, after: 80 },
    children: [new TextRun({ text, color: JAM_GREEN, bold: true, size: 28 })],
  });
}
function h3(text: string) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 160, after: 60 },
    children: [new TextRun({ text, color: JAM_GOLD, bold: true, size: 22 })],
  });
}
function p(text: string, opts: { italic?: boolean; bold?: boolean } = {}) {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, italics: opts.italic, bold: opts.bold, size: 22 })],
  });
}
function bullet(text: string) {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text, size: 22 })],
  });
}
function numbered(text: string, n: number) {
  return new Paragraph({
    spacing: { after: 80 },
    children: [new TextRun({ text: `${n}. ${text}`, size: 22 })],
  });
}

function rubricTable(rubric: any): Table {
  const border = { style: BorderStyle.SINGLE, size: 4, color: "B7AC81" };
  const borders = { top: border, bottom: border, left: border, right: border };

  const headerRow = new TableRow({
    tableHeader: true,
    children: [
      "Criterion",
      "Weight",
      "Distinguished",
      "Proficient",
      "Developing",
      "Emerging",
    ].map(
      (text) =>
        new TableCell({
          borders,
          shading: { type: ShadingType.CLEAR, color: "auto", fill: JAM_GREEN },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text, bold: true, color: "FFFFFF", size: 20 })],
            }),
          ],
        })
    ),
  });

  const rows = rubric.criteria.map(
    (c: any) =>
      new TableRow({
        children: [
          new TableCell({
            borders,
            shading: { type: ShadingType.CLEAR, color: "auto", fill: "F4ECCB" },
            children: [
              new Paragraph({
                children: [new TextRun({ text: c.name, bold: true, size: 20 })],
              }),
              new Paragraph({
                children: [
                  new TextRun({
                    text: `Outcomes: ${(c.outcomesAddressed || []).join(", ") || "—"}`,
                    italics: true,
                    size: 18,
                    color: "555555",
                  }),
                ],
              }),
            ],
          }),
          new TableCell({
            borders,
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: `${c.weight}%`, bold: true, size: 20 })],
              }),
            ],
          }),
          ...["Distinguished", "Proficient", "Developing", "Emerging"].map(
            (lvl) =>
              new TableCell({
                borders,
                children: [new Paragraph({ children: [new TextRun({ text: c.levels[lvl], size: 18 })] })],
              })
          ),
        ],
      })
  );

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...rows],
  });
}

export async function downloadDocx(payload: DesignPayload) {
  const { context, lens, outcomes, brief, integrity, rubric, alignmentReport, patoisMode } =
    payload;
  const children: any[] = [];

  // Title block
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
      children: [
        new TextRun({
          text: "SOVEREIGN AI LEARNING DESIGN",
          color: JAM_GOLD,
          bold: true,
          size: 18,
        }),
      ],
    })
  );
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [
        new TextRun({
          text: brief?.title || "Assignment",
          color: JAM_GREEN,
          bold: true,
          size: 44,
        }),
      ],
    })
  );

  // Metadata table
  children.push(h2("Course context"));
  const metaRows = [
    ["Course", context.courseTitle],
    ["Discipline", context.discipline],
    ["Level", context.level],
    ["Region", context.region],
    ["Modality", context.modality],
    ["Time on task", context.timeOnTask],
    ["AI sovereignty stance", context.aiAccess],
    ["Reflection lens", lens],
  ];
  if (patoisMode) metaRows.push(["Register", "Patois-aware mode enabled"]);

  const metaTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: metaRows.map(
      ([k, v]) =>
        new TableRow({
          children: [
            new TableCell({
              shading: { type: ShadingType.CLEAR, color: "auto", fill: "F4ECCB" },
              children: [new Paragraph({ children: [new TextRun({ text: k, bold: true, size: 20 })] })],
            }),
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: String(v || "—"), size: 20 })] })],
            }),
          ],
        })
    ),
  });
  children.push(metaTable);

  // Outcomes
  if (outcomes.length) {
    children.push(h2("Learning outcomes"));
    outcomes.forEach((o: any, i: number) => children.push(numbered(`${o.statement}  [${o.bloomLevel}]`, i + 1)));
  }

  // Brief
  if (brief) {
    children.push(h2("Assignment brief"));
    children.push(p(brief.summary, { italic: true }));
    children.push(h3("Scenario"));
    children.push(p(brief.scenario));
    children.push(h3("Tasks"));
    brief.tasks.forEach((t: string, i: number) => children.push(numbered(t, i + 1)));
    children.push(h3("Deliverables"));
    brief.deliverables.forEach((d: string) => children.push(bullet(d)));

    if (brief.criticalReflectionPrompts?.length) {
      children.push(h3("CARE reflection prompts"));
      brief.criticalReflectionPrompts.forEach((q: any) =>
        children.push(p(`${q.stage}: ${q.prompt}`))
      );
    }
    children.push(h3("AI use guidance"));
    children.push(p(brief.aiUseGuidance));
  }

  // Integrity
  if (integrity) {
    children.push(h2("AI integrity & sovereignty statement"));
    children.push(h3("Permitted uses"));
    integrity.permittedUses.forEach((u: string) => children.push(bullet(u)));
    children.push(h3("Restricted uses"));
    integrity.restrictedUses.forEach((u: any) => children.push(bullet(`${u.item} — ${u.reason}`)));
    children.push(h3("Disclosure requirement"));
    children.push(p(integrity.disclosureRequirement, { italic: true }));
    if (patoisMode && integrity.studentFacingPatois) {
      children.push(h3("Disclosure — Patois register"));
      children.push(p(integrity.studentFacingPatois, { italic: true }));
    }
    children.push(h3("CARE reflection"));
    children.push(p(integrity.careReflection));
    children.push(h3("ACRE evaluation"));
    children.push(p(integrity.acreEvaluation));
    children.push(h3("Sovereignty note"));
    children.push(p(integrity.sovereigntyNote, { italic: true }));
  }

  // Rubric
  if (rubric) {
    children.push(h2("Aligned rubric"));
    children.push(rubricTable(rubric));
  }

  // Alignment audit
  if (alignmentReport) {
    children.push(h2("Alignment audit"));
    children.push(p(`Overall: ${alignmentReport.overallScore}`, { bold: true }));
    children.push(p(alignmentReport.summary));
    if (alignmentReport.orphanOutcomes?.length) {
      children.push(h3("Outcomes not measured by any criterion"));
      alignmentReport.orphanOutcomes.forEach((o: any) =>
        children.push(bullet(`Outcome ${o.index}: ${o.statement} — Fix: ${o.fix}`))
      );
    }
    if (alignmentReport.orphanCriteria?.length) {
      children.push(h3("Criteria with weak outcome alignment"));
      alignmentReport.orphanCriteria.forEach((c: any) =>
        children.push(bullet(`${c.name} — Fix: ${c.fix}`))
      );
    }
  }

  // Footer
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 480 },
      border: { top: { style: BorderStyle.SINGLE, size: 4, color: JAM_GREEN } },
      children: [
        new TextRun({
          text: ATTRIBUTION,
          italics: true,
          color: "555555",
          size: 18,
        }),
      ],
    })
  );

  const doc = new Document({
    creator: "Dr. Rohan Jowallah, Ed.D.",
    title: brief?.title || "Sovereign AI Assignment",
    description: "Generated by the Sovereign AI Learning Designer",
    styles: {
      default: {
        document: { run: { font: "Calibri" } },
      },
    },
    sections: [
      {
        properties: {
          page: { size: { orientation: PageOrientation.PORTRAIT } },
        },
        children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${safeFilename(brief?.title)}-sovereign-package.docx`);
}

/* ---------------- PDF ---------------- */

export function downloadPdf(payload: DesignPayload) {
  const { context, lens, outcomes, brief, integrity, rubric, alignmentReport, patoisMode } =
    payload;

  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 54;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensure = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const title = (text: string) => {
    ensure(36);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 107, 60); // JAM_GREEN
    doc.setFontSize(18);
    doc.text(text, margin, y);
    y += 24;
  };

  const heading = (text: string) => {
    ensure(28);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(201, 154, 0); // JAM_GOLD_DEEP
    doc.setFontSize(13);
    doc.text(text.toUpperCase(), margin, y);
    y += 16;
    doc.setDrawColor(217, 207, 169);
    doc.line(margin, y - 4, pageWidth - margin, y - 4);
  };

  const para = (text: string, opts: { italic?: boolean; bold?: boolean } = {}) => {
    if (!text) return;
    doc.setFont("helvetica", opts.bold ? "bold" : opts.italic ? "italic" : "normal");
    doc.setTextColor(26, 26, 26);
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      ensure(15);
      doc.text(line, margin, y);
      y += 14;
    });
    y += 4;
  };

  const list = (items: string[], numbered = false) => {
    items.forEach((item, i) => {
      const prefix = numbered ? `${i + 1}. ` : "• ";
      const text = prefix + item;
      const lines = doc.splitTextToSize(text, maxWidth - 10);
      lines.forEach((line: string, idx: number) => {
        ensure(15);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(26, 26, 26);
        doc.setFontSize(11);
        doc.text(line, margin + (idx === 0 ? 0 : 12), y);
        y += 14;
      });
    });
    y += 4;
  };

  // Header band
  doc.setFillColor(0, 107, 60);
  doc.rect(0, 0, pageWidth, 8, "F");
  doc.setFillColor(254, 209, 0);
  doc.rect(0, 8, pageWidth, 4, "F");
  doc.setFillColor(26, 26, 26);
  doc.rect(0, 12, pageWidth, 2, "F");
  y = margin + 6;

  doc.setFont("helvetica", "bold");
  doc.setTextColor(201, 154, 0);
  doc.setFontSize(9);
  doc.text("SOVEREIGN AI LEARNING DESIGN", margin, y);
  y += 16;

  title(brief?.title || "Assignment");

  // Context
  heading("Course context");
  para(`Course: ${context.courseTitle}`);
  para(`Discipline: ${context.discipline}`);
  para(`Level: ${context.level}    Region: ${context.region}    Modality: ${context.modality}`);
  para(`Time on task: ${context.timeOnTask}`);
  para(`AI sovereignty stance: ${context.aiAccess}    Reflection lens: ${lens}`);
  if (patoisMode) para("Register: Patois-aware mode enabled", { italic: true });

  if (outcomes.length) {
    heading("Learning outcomes");
    list(outcomes.map((o: any) => `${o.statement}  [${o.bloomLevel}]`), true);
  }

  if (brief) {
    heading("Brief");
    para(brief.summary, { italic: true });
    para("Scenario", { bold: true });
    para(brief.scenario);
    para("Tasks", { bold: true });
    list(brief.tasks, true);
    para("Deliverables", { bold: true });
    list(brief.deliverables);
    if (brief.criticalReflectionPrompts?.length) {
      para("CARE reflection prompts", { bold: true });
      list(brief.criticalReflectionPrompts.map((q: any) => `${q.stage}: ${q.prompt}`));
    }
    para("AI use guidance", { bold: true });
    para(brief.aiUseGuidance);
  }

  if (integrity) {
    heading("AI integrity & sovereignty statement");
    para("Permitted uses", { bold: true });
    list(integrity.permittedUses);
    para("Restricted uses", { bold: true });
    list(integrity.restrictedUses.map((u: any) => `${u.item} — ${u.reason}`));
    para("Disclosure requirement", { bold: true });
    para(integrity.disclosureRequirement, { italic: true });
    if (patoisMode && integrity.studentFacingPatois) {
      para("Disclosure (Patois register)", { bold: true });
      para(integrity.studentFacingPatois, { italic: true });
    }
    para("CARE reflection", { bold: true });
    para(integrity.careReflection);
    para("ACRE evaluation", { bold: true });
    para(integrity.acreEvaluation);
    para("Sovereignty note", { bold: true });
    para(integrity.sovereigntyNote, { italic: true });
  }

  if (rubric) {
    heading("Aligned rubric");
    rubric.criteria.forEach((c: any) => {
      para(`${c.name}  (${c.weight}%)  outcomes: ${(c.outcomesAddressed || []).join(", ") || "—"}`, { bold: true });
      ["Distinguished", "Proficient", "Developing", "Emerging"].forEach((lvl) => {
        para(`${lvl}: ${c.levels[lvl]}`);
      });
    });
  }

  if (alignmentReport) {
    heading("Alignment audit");
    para(`Overall: ${alignmentReport.overallScore}`, { bold: true });
    para(alignmentReport.summary);
    if (alignmentReport.orphanOutcomes?.length) {
      para("Outcomes not measured", { bold: true });
      list(alignmentReport.orphanOutcomes.map((o: any) => `Outcome ${o.index}: ${o.statement} — Fix: ${o.fix}`));
    }
    if (alignmentReport.orphanCriteria?.length) {
      para("Criteria with weak alignment", { bold: true });
      list(alignmentReport.orphanCriteria.map((c: any) => `${c.name} — Fix: ${c.fix}`));
    }
  }

  // Footer on last page
  ensure(40);
  y += 12;
  doc.setDrawColor(0, 107, 60);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;
  doc.setFont("helvetica", "italic");
  doc.setTextColor(85, 85, 85);
  doc.setFontSize(9);
  const footerLines = doc.splitTextToSize(ATTRIBUTION, maxWidth);
  footerLines.forEach((line: string) => {
    doc.text(line, margin, y);
    y += 11;
  });

  // Page numbers
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.setFontSize(9);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 18, {
      align: "right",
    });
  }

  doc.save(`${safeFilename(brief?.title)}-sovereign-package.pdf`);
}

/* ---------------- Copy LMS to clipboard ---------------- */

export async function copyLmsToClipboard(payload: DesignPayload) {
  const md = buildLmsBlock(payload);
  await navigator.clipboard.writeText(md);
  return md;
}
